var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var __extends = this && this.__extends || function __extends(t, e) { 
 function r() { 
 this.constructor = t;
}
for (var i in e) e.hasOwnProperty(i) && (t[i] = e[i]);
r.prototype = e.prototype, t.prototype = new r();
};
var LootPanel = (function (_super) {
    __extends(LootPanel, _super);
    function LootPanel() {
        var _this = _super.call(this, 200, 230) || this;
        _this.beginX = 10;
        _this.beginY = 30;
        _this.gap = 25;
        _this.fontSize = 20;
        _this.gapX = 100;
        _this.money = 0;
        _this.exp = 0;
        _this.basic = 0;
        _this.magic = 0;
        _this.rare = 0;
        _this.perfect = 0;
        _this.epic = 0;
        _this.legendary = 0;
        var cell = new StringCell("当前地图掉落", 150, 24);
        _this.addChild(cell);
        cell.x = 5;
        cell.y = 5;
        cell = new StringCell("<font color=\'#FFA640\'>$</font>", 100, _this.fontSize);
        _this.addChild(cell);
        cell.x = _this.beginX;
        cell.y = _this.beginY;
        cell = new StringCell("<font color=\'#4a60d7\'>EXP", 100, _this.fontSize);
        _this.addChild(cell);
        cell.x = _this.beginX;
        cell.y = _this.beginY + _this.gap;
        cell = new StringCell("普通", 100, _this.fontSize);
        _this.addChild(cell);
        cell.x = _this.beginX;
        cell.y = _this.beginY + _this.gap * 2;
        cell = new StringCell("<font color=\'" + iData.iItem.Equipment.GREEN + "\'>精品</font>", 100, _this.fontSize);
        _this.addChild(cell);
        cell.x = _this.beginX;
        cell.y = _this.beginY + _this.gap * 3;
        cell = new StringCell("<font color=\'" + iData.iItem.Equipment.BLUE + "\'>稀有</font>", 100, _this.fontSize);
        _this.addChild(cell);
        cell.x = _this.beginX;
        cell.y = _this.beginY + _this.gap * 4;
        cell = new StringCell("<font color=\'" + iData.iItem.Equipment.YELLOW + "\'>完美</font>", 100, _this.fontSize);
        _this.addChild(cell);
        cell.x = _this.beginX;
        cell.y = _this.beginY + _this.gap * 5;
        cell = new StringCell("<font color=\'" + iData.iItem.Equipment.ORANGE + "\'>史诗</font>", 100, _this.fontSize);
        _this.addChild(cell);
        cell.x = _this.beginX;
        cell.y = _this.beginY + _this.gap * 6;
        cell = new StringCell("<font color=\'" + iData.iItem.Equipment.PURPLE + "\'>传奇</font>", 100, _this.fontSize);
        _this.addChild(cell);
        cell.x = _this.beginX;
        cell.y = _this.beginY + _this.gap * 7;
        _this.money_c = new StringCell("0", 65, _this.fontSize);
        _this.addChild(_this.money_c);
        _this.money_c.x = _this.beginX + _this.gapX;
        _this.money_c.y = _this.beginY;
        _this.exp_c = new StringCell("0", 65, _this.fontSize);
        _this.addChild(_this.exp_c);
        _this.exp_c.x = _this.beginX + _this.gapX;
        _this.exp_c.y = _this.beginY + _this.gap * 1;
        _this.basic_c = new StringCell("0", 65, _this.fontSize);
        _this.addChild(_this.basic_c);
        _this.basic_c.x = _this.beginX + _this.gapX;
        _this.basic_c.y = _this.beginY + _this.gap * 2;
        _this.magic_c = new StringCell("0", 65, _this.fontSize);
        _this.addChild(_this.magic_c);
        _this.magic_c.x = _this.beginX + _this.gapX;
        _this.magic_c.y = _this.beginY + _this.gap * 3;
        _this.rare_c = new StringCell("0", 65, _this.fontSize);
        _this.addChild(_this.rare_c);
        _this.rare_c.x = _this.beginX + _this.gapX;
        _this.rare_c.y = _this.beginY + _this.gap * 4;
        _this.perfect_c = new StringCell("0", 65, _this.fontSize);
        _this.addChild(_this.perfect_c);
        _this.perfect_c.x = _this.beginX + _this.gapX;
        _this.perfect_c.y = _this.beginY + _this.gap * 5;
        _this.epic_c = new StringCell("0", 65, _this.fontSize);
        _this.addChild(_this.epic_c);
        _this.epic_c.x = _this.beginX + _this.gapX;
        _this.epic_c.y = _this.beginY + _this.gap * 6;
        _this.legendary_c = new StringCell("0", 65, _this.fontSize);
        _this.addChild(_this.legendary_c);
        _this.legendary_c.x = _this.beginX + _this.gapX;
        _this.legendary_c.y = _this.beginY + _this.gap * 7;
        return _this;
    }
    LootPanel.prototype.reset = function () {
        this.money = (0);
        this.exp = (0);
        this.basic = (0);
        this.magic = (0);
        this.rare = (0);
        this.perfect = (0);
        this.epic = (0);
        this.legendary = (0);
    };
    LootPanel.prototype.update = function () {
        this.money_c.setText(this.money + "");
        this.exp_c.setText(this.exp + "");
        this.basic_c.setText(this.basic + "");
        this.magic_c.setText(this.magic + "");
        this.rare_c.setText(this.rare + "");
        this.perfect_c.setText(this.perfect + "");
        this.epic_c.setText(this.epic + "");
        this.legendary_c.setText(this.legendary + "");
    };
    return LootPanel;
}(BasicCell));
__reflect(LootPanel.prototype, "LootPanel");
